import * as XLSX from 'xlsx';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

/**
 * High-fidelity Excel to PDF conversion
 * Features:
 * - Multi-sheet support
 * - Auto-paging
 * - Smart column width calculation
 * - Professional table styling
 * @param {File} file - The Excel file object
 * @returns {Promise<Object>} - Download URL and filename
 */
export const convertExcelToPdf = async (file) => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();

    reader.onload = async (e) => {
      try {
        const data = new Uint8Array(e.target.result);
        const workbook = XLSX.read(data, { type: 'array', cellDates: true, cellStyles: true });
        
        const doc = new jsPDF({
          orientation: 'landscape',
          unit: 'mm',
          format: 'a4'
        });

        const totalSheets = workbook.SheetNames.length;
        
        workbook.SheetNames.forEach((sheetName, index) => {
          const worksheet = workbook.Sheets[sheetName];
          
          // Convert sheet to JSON array
          const jsonData = XLSX.utils.sheet_to_json(worksheet, { header: 1, defval: "" });
          
          if (jsonData.length === 0) return;

          // Add sheet title
          if (index > 0) doc.addPage();
          
          doc.setFontSize(14);
          doc.setTextColor(44, 62, 80); // Dark Blueish Grey
          doc.text(`Sheet: ${sheetName}`, 14, 15);
          doc.setFontSize(10);
          doc.setTextColor(127, 140, 141); // Grey
          doc.text(`Generated by CodeFix Tool`, 14, 22);

          // Prepare headers and body
          const headers = [jsonData[0]]; // First row as header
          const body = jsonData.slice(1);

          // Generate Table using direct autoTable call
          autoTable(doc, {
            head: headers,
            body: body,
            startY: 30,
            theme: 'striped',
            styles: {
              fontSize: 8,
              cellPadding: 3,
              font: 'helvetica',
              textColor: [50, 50, 50],
              lineColor: [200, 200, 200],
              lineWidth: 0.1,
            },
            headStyles: {
              fillColor: [59, 130, 246], // CodeFix Primary Blue
              textColor: [255, 255, 255],
              fontSize: 9,
              fontStyle: 'bold',
              halign: 'center'
            },
            alternateRowStyles: {
              fillColor: [245, 247, 250]
            },
            margin: { top: 30, bottom: 20, left: 14, right: 14 },
            didDrawPage: (data) => {
              // Footer: Page numbers
              doc.setFontSize(8);
              doc.setTextColor(150);
              const pageSize = doc.internal.pageSize;
              const pageHeight = pageSize.height ? pageSize.height : pageSize.getHeight();
              const pageWidth = pageSize.width ? pageSize.width : pageSize.getWidth();
              doc.text(
                `Page ${doc.internal.getNumberOfPages()}`,
                pageWidth / 2,
                pageHeight - 10,
                { align: 'center' }
              );
            }
          });
        });

        const pdfBlob = doc.output('blob');
        const downloadUrl = URL.createObjectURL(pdfBlob);
        const fileName = file.name.replace(/\.[^/.]+$/, "") + ".pdf";

        resolve({
          downloadUrl,
          fileName,
          stats: {
            sheets: totalSheets,
            originalSize: (file.size / 1024).toFixed(2) + " KB"
          }
        });
      } catch (error) {
        console.error("Excel to PDF conversion failed:", error);
        reject(error);
      }
    };

    reader.onerror = (error) => reject(error);
    reader.readAsArrayBuffer(file);
  });
};
